### ISSUE TITLE
ModuleNotFoundError: No module named 'MySQLdb'

### ISSUE THREAD

**Issue by lafrenbl-osu** [kszirtidis/Assignment-8#2]
init_db.py:

```
from Blaine_microservice import app, db

with app.app_context():
  db.create_all()
```

```
➜  Assignment-8 git:(main) ✗ python init_db.py
Traceback (most recent call last):
  File "/Users/blaine/Documents/CS 361 - Software Engineering/Assignment-8/init_db.py", line 1, in <module>
    from Blaine_microservice import app, db
  File "/Users/blaine/Documents/CS 361 - Software Engineering/Assignment-8/Blaine_microservice.py", line 6, in <module>
    db = SQLAlchemy(app)
         ^^^^^^^^^^^^^^^
  File "/Users/blaine/.asdf/installs/python/3.12.3/lib/python3.12/site-packages/flask_sqlalchemy/extension.py", line 219, in __init__
    self.init_app(app)
  File "/Users/blaine/.asdf/installs/python/3.12.3/lib/python3.12/site-packages/flask_sqlalchemy/extension.py", line 320, in init_app
    engines[key] = self._make_engine(key, options, app)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blaine/.asdf/installs/python/3.12.3/lib/python3.12/site-packages/flask_sqlalchemy/extension.py", line 606, in _make_engine
    return sa.engine_from_config(options, prefix="")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blaine/.asdf/installs/python/3.12.3/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 820, in engine_from_config
    return create_engine(url, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/Users/blaine/.asdf/installs/python/3.12.3/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/blaine/.asdf/installs/python/3.12.3/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 599, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blaine/.asdf/installs/python/3.12.3/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 147, in import_dbapi
    return __import__("MySQLdb")
           ^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'MySQLdb'
```

Should I be using a specific version of Python?

Seems like there might be some missing dependencies that aren't specified within `requirements.txt`

If you do `pip freeze` it will show you everything installed in your `site-packages` folder, and what version it is.

**Comment by lafrenbl-osu** [comment]
maybe try `pip freeze | grep -i mysql`

**Comment by lafrenbl-osu** [comment]
ok, I think I got it working. I had to install some local libraries on my Mac, and then install `mysqlclient` as a pip dependency.

**Comment by kszirtidis** [comment]
Closing the issue as teammate stated he believes he has it working.
